development:
  adapter: sqlite3
  database: db/madlibs.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mydb
  pool: 25
  url: <%= ENV['DATABASE_URL'] %>